services:
  api:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./backend/prisma:/usr/src/app/prisma
      - ./backend/uploads:/usr/src/app/uploads
  web:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
